// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhglnD3QOEqmZPt2czSIsfFi5MDYkV7s0',
    appId: '1:1091472604781:web:7de167cef73f0e94a10964',
    messagingSenderId: '1091472604781',
    projectId: 'agroautomated-8f55e',
    authDomain: 'agroautomated-8f55e.firebaseapp.com',
    databaseURL: 'https://agroautomated-8f55e-default-rtdb.firebaseio.com',
    storageBucket: 'agroautomated-8f55e.appspot.com',
    measurementId: 'G-R1BNFSHFPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb77Sf8ZljRAsoGgb_QaEOl_sKoLjaL7k',
    appId: '1:1091472604781:android:efbc463172b287eba10964',
    messagingSenderId: '1091472604781',
    projectId: 'agroautomated-8f55e',
    databaseURL: 'https://agroautomated-8f55e-default-rtdb.firebaseio.com',
    storageBucket: 'agroautomated-8f55e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClFRIkvdESOqb9yor1XEFIfe29mSiAI3M',
    appId: '1:1091472604781:ios:19ce2a6b95a3283ea10964',
    messagingSenderId: '1091472604781',
    projectId: 'agroautomated-8f55e',
    databaseURL: 'https://agroautomated-8f55e-default-rtdb.firebaseio.com',
    storageBucket: 'agroautomated-8f55e.appspot.com',
    iosBundleId: 'com.example.agroautomated',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClFRIkvdESOqb9yor1XEFIfe29mSiAI3M',
    appId: '1:1091472604781:ios:d9ba6f800c1aee64a10964',
    messagingSenderId: '1091472604781',
    projectId: 'agroautomated-8f55e',
    databaseURL: 'https://agroautomated-8f55e-default-rtdb.firebaseio.com',
    storageBucket: 'agroautomated-8f55e.appspot.com',
    iosBundleId: 'com.example.agroautomated.RunnerTests',
  );
}
